import type { Metadata } from "next";
import { Geist, Lato } from "next/font/google";
import "@/assets/scss/globals.scss";

const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geist.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}

