import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@/assets/scss/globals.scss";

const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const HamburgerIcon = () => (
  <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
    <line x1="3" y1="12" x2="21" y2="12"></line>
    <line x1="3" y1="6" x2="21" y2="6"></line>
    <line x1="3" y1="18" x2="21" y2="18"></line>
  </svg>
);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geist.className} antialiased bg-[#F9F8F4] min-h-screen`}>
        <header className="py-6 px-4 flex justify-between items-center bg-white shadow-sm">
          <HamburgerIcon />
        </header>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}

