import type { Metadata } from "next";
import { Geist } from "next/font/google";
import "@/assets/scss/globals.scss";

import Header from "@/components/common/Header";

const geist = Geist({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={`${geist.className} antialiased bg-[#F9F8F4] min-h-screen`}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}

